### ISSUE TITLE
In Firefox, div's scrollbar is visible underneath nanoscroll bar, but not in Chrome?

### ISSUE THREAD

**Issue by flyingace** [jamesflorentino/nanoScrollerJS#171]
http://www.davidcameron.biz

In Firefox (v20.0.1 & v23 --just updated) on Windows XP, the div's vertical scrollbar is always visible if the content is too tall. The nanoscroller bar fades in and out on top of the div's scrollbar when content is hovered over.

This behavior does not appear in Chrome (v 28.0.1500.95 m), or in any of the mobile browsers where I have tested the site.

**Comment by Chactas** [comment]
Just wondering if anyone found a solution to this? I can see on your website that when I zoom out the default scrollbar is still there!

**Comment by niravpatel9898** [comment]
thanks a lot !! just removing the width of nano-container which was 100% solved the issue
made my day

**Comment by elboletaire** [comment]
> Just wondering if anyone found a solution to this? I can see on your website that when I zoom out the default scrollbar is still there!

Why are you zooming out? xD

**Comment by brengrg** [comment]
Hi all 
This script worked for me, just load the scrolling content from external html file eg. list.html

<div id="notification" class="nano report-notification">
         <div class="nano-content description"> </div>
 </div>
<script>
        $(function () {

            $('.nano').nanoScroller({
                preventPageScrolling: true
            });
            $("#notification").find('.description').load("list.html", function () {
                $(".nano").nanoScroller();
                $("#notification").find("img").load(function () {
                    $(".nano").nanoScroller();
                });
            });


        });
    </script>
