### ISSUE TITLE
Firefox: native scrollbar visible

### ISSUE THREAD

**Issue by ghost** [jamesflorentino/nanoScrollerJS#218]
In my app .nano and .nano-content are children of a div element with an opacity set to 0.7.

While this seems to cause no issues in Chrome, the native scollbar of the .nano-content is visible in FF.

Any ideas how I can prevent this?

**Comment by petebarr** [comment]
Great to know! I had a margin-right on the nano-content which also resulted in native scrollbars for Firefox and IE. Padding-right instead works great. Cheers!
