### ISSUE TITLE
Support of IE8 is broken since jQuery 1.11.0

### ISSUE THREAD

**Issue by JSteunou** [jamesflorentino/nanoScrollerJS#232]
With nanoScroller 0.7.6 to 0.8.0 + jQuery 1.11.0 mouse scroll is broken and scroll while grapping the bar is slow & laggy.

All is fine with jQuery 1.10.2

You can reproduce this by changing your jQuery version on you own demo page.

**Comment by calledT** [comment]
also have this problem

**Comment by kristerkari** [comment]
@calledT Could you give me more details about your problem? Also if you have a link to a demo with the problem that would be great.
