### ISSUE TITLE
Native Scrollbar Padding Visible in Chrome 37 Mac OS X

### ISSUE THREAD

**Issue by andyvenus** [jamesflorentino/nanoScrollerJS#255]
Today Chrome updated me to Chrome 37 and I found that nanoscroller containers were showing a space where the original scrollbar should appear. 

Here is Chrome 36 vs Chrome 37:

![example](https://cloud.githubusercontent.com/assets/5107023/4074945/d44a8eaa-2ea7-11e4-997e-05494b9e930e.png)

It seems that 

```
.nano > .nano-content::-webkit-scrollbar {
  visibility: hidden;
}
```

Doesn't totally remove the scroll bar in version 37+ on Mac OS X (and is still the case in the latest Canary build). This doesn't seem to affect Windows.

I was able to fix it by adding 

```
width: 0px;
```

To the above CSS class.

**Comment by mikealmond** [comment]
Unfortunately this is not fixed on OS X for all situations. There is a setting under `System Preferences > General` that impacts the scrollbar width calculation. 

When the "Show scroll bar" setting is set to "Always" the nano scroller sets the width properly. If it's set to "Automatically based on mouse or trackpad", it does not and still has the 16px gap.

Does anybody have an idea on how to fix this?

**Comment by kristerkari** [comment]
@mikealmond I'm using "Automatically based on mouse or trackpad" and it seems to work fine. Which browser are you using? Is the problem visible on nanoScroller website/demo?

**Comment by mikealmond** [comment]
You can see the gap in the code block in the screenshots below.

When set to "Always"
![screen shot 2015-04-13 at 2 21 13 pm](https://cloud.githubusercontent.com/assets/600744/7122287/73aa5e82-e1e8-11e4-8ee6-6ada724649c0.png)

When set to "Automatically based on mouse or trackpad"
![screen shot 2015-04-13 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/600744/7122295/83ddc03c-e1e8-11e4-86b6-9fbe91c48743.png)

**Comment by kristerkari** [comment]
True, but only seems to happen if I change the setting when a page that has nanoScroller is currently open. If I refresh the page the padding is normal again.

**Comment by mikealmond** [comment]
I did a hard refresh after I change the system setting and then took the screenshots.

**Comment by kristerkari** [comment]
Which OS X version and which browser and browser version are you using?

**Comment by mikealmond** [comment]
OS X 10.10.3
Chrome 42.0.2311.82 beta (64bit).

Tested on Safari 8.0.5 and Chrome 41 as well as on a retina and non-retina screen. All did the same thing.

**Comment by kristerkari** [comment]
Thanks, I was using Firefox, but I'll try with other browsers.

**Comment by kristerkari** [comment]
Oh yeah https://jamesflorentino.github.io/nanoScrollerJS/ uses version 0.8.1 that did not have this fix yet. 

I tried with Safari and the bug exists with https://jamesflorentino.github.io/nanoScrollerJS/ but not with the newest nanoScroller version.

Time to update Github pages... :)

**Comment by kristerkari** [comment]
@mikealmond I have updated Github pages to the latest nanoScroller version (0.8.6), let me know if you still see the problem (it went away for me).

**Comment by mikealmond** [comment]
Looks like the example is fixed for me. 

I also discovered my issue was related to a left over `.content` class not being updated. Thanks for your help!
