### ISSUE TITLE
preventPageScrolling in IE not working

### ISSUE THREAD

**Issue by jamezamm** [jamesflorentino/nanoScrollerJS#273]
**preventPageScrolling: true** does not completely block page scrolling in internet explorer. The first time the scrollbar hits top or bottom, the page scrolls for an instant.

Thanks.

**Comment by FlorianMaak** [comment]
Are there any plans to fix this issue soon? :)

**Comment by kristerkari** [comment]
> Are there any plans to fix this issue soon? :)

@FlorianMaak sorry for the slow reply.. I'm having trouble finding enough time to maintain this project, so I have mainly just been marking issues as bugs etc.

I'll have to see if I could reserve one weekend to fix some of the bugs here.
