### ISSUE TITLE
'scrollend' event doesn't fire on iOS8 Safari

### ISSUE THREAD

**Issue by issunboshi** [jamesflorentino/nanoScrollerJS#282]
Hi,

When listening for the 'scrollend' event on an iOS device (tested with 3rd Gen iPad and 1 gen iPad Mini) running iOS 8 nothing is triggered. However running on the same devices on iOS 7 works as expected.

I understand that there was a significant change to scroll behaviour in iOS 8 (http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/). Perhaps this has caused issues?

For now I've set iOSNativeScrolling:true, which does mean the event is triggered. However ideally it would be the same for iOS as other devices.

Thanks,

Cliff

**Comment by kristerkari** [comment]
Thanks, this needs to be investigated.
