### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by SimenB** [jamesflorentino/nanoScrollerJS#291]
Please? :smile: 

It's the official way to distribute jQuery plugins. https://plugins.jquery.com/

**Comment by kristerkari** [comment]
Sure thing.

**Comment by kristerkari** [comment]
`npm publish` is returning status 500 for me at the moment, so no npm release yet :) I'll try again later so let's keep this open.

**Comment by SimenB** [comment]
You have to create a user, probably.
http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick

**Comment by kristerkari** [comment]
I have a user created:
```
↳ npm whoami
kristerkari
```
Probably something else wrong...

**Comment by SimenB** [comment]
Ah, ok. Nothing reported at their status, though. http://status.npmjs.org/

**Comment by SimenB** [comment]
Ah, ok. Nothing reported at their status, though. http://status.npmjs.org/

EDIT: @kristerkari just tried to publish to test, and it works fine now. Removed myself as owner, and added you.

```shell
npm owner ls nanoscroller
kristerkari <krister.kari@webtehdas.fi>
```

**Comment by kristerkari** [comment]
@SimenB Thanks!

**Comment by calebboyd** [comment]
It looks like the `main` field is incorrect (or incorrect files are published) in the npm package.

**Comment by SimenB** [comment]
Yeah, main is missing `bin/` prefix. Sorry about that... :S
But the `bin` directory is included, right? You just have to `require`
manually inside the package?

**Comment by calebboyd** [comment]
Yeah you can still use it but is broken for other managers (jspm)

**Comment by SimenB** [comment]
#283 seems to be where it came from. I probably should have noticed it in #292, though...

**Comment by kristerkari** [comment]
Doh, I'll have to push a new version then.

**Comment by SimenB** [comment]
@kristerkari Throwing together a PR now, gimme 5 min

**Comment by calebboyd** [comment]
On another note, it works great as a github install on jspm

**Comment by SimenB** [comment]
@calebboyd, ok, so the stuff from #283 is correct, it's only the `main`-field messing up when it's from npm?

**Comment by calebboyd** [comment]
Yeah, github/jspm install works fine. its just for npm that it appears to be broken.

**Comment by scoarescoare** [comment]
@SimenB `bin/` is included, in a way, because it's defined as the [directories.lib](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#directorieslib) config parameter.

**Comment by SimenB** [comment]
Ok, cool. The more you know :smile:

**Comment by kristerkari** [comment]
Thanks for the fixes guys.

Does npm see the changes now, or is there a need to to publish a new version?

**Comment by SimenB** [comment]
You'll need to publish

**Comment by kristerkari** [comment]
version 0.8.7 is out

**Comment by domialex** [comment]
Is it possible to change the `bin` directory to `dist` or something similar? Since bin is blocked by IIS and some other webservers.
