### ISSUE TITLE
HTML code removed when scrolling down

### ISSUE THREAD

**Issue by WTenpa** [jamesflorentino/nanoScrollerJS#299]
Hi, I'm in trouble with Nanoscroller.

I've installed it on my project and it seems to work normally but, when I scroll down, the whole html code inside the .nano class is litterally removed!

Is that a bug, or did I miss something?

**Comment by kristerkari** [comment]
Well hard to say without seeing your code. Have you followed the instructions in README and had a look at how the demo for nanoScroller is set up?

**Comment by kristerkari** [comment]
Closing as inactive, let's reopen if something new comes up.
