### ISSUE TITLE
dynamic content

### ISSUE THREAD

**Issue by Nageshwari-p** [jamesflorentino/nanoScrollerJS#321]
scroll bar not working if content is adding dynamically . Example chat .

please help in this its very urgent

**Comment by RiCoTeRoX** [comment]
you must update the scroller

**Comment by tyuqing** [comment]
In the case proposed by @Nageshwari-p ,what event should be listened to update the scroller? @RiCoTeRoX

**Comment by RiCoTeRoX** [comment]
read the documentation does not hurt. @Nageshwari-p 
https://github.com/jamesflorentino/nanoScrollerJS#nanoscroller
