### ISSUE TITLE
No source files on NPM?

### ISSUE THREAD

**Issue by SimonSchick** [jamesflorentino/nanoScrollerJS#325]
It seems the source files (less/scss) are not shipped to npm, they are shipped to bower however.
This is kind of silly because now I have to use bower for only this dependency.

**Comment by fredrkr** [comment]
It's not just the source-files that are missing. The minified versions are also missing, which is indeed silly for a plugin published on NPM.

**Comment by piperone** [comment]
Why would you close this? The files are still missing from the NPM-package.

**Comment by SimonSchick** [comment]
Just closed a bunch of issues that seems like `wontfix` or are irrelevant to me now, this package has been last updated in 10 months.

**Comment by piperone** [comment]
It might be irrelevant to you, but you are definitely not helping by closing it. Also, there is no wontfix-label, so you can't know that it is. Please reopen.
