### ISSUE TITLE
Save scroll position 

### ISSUE THREAD

**Issue by di3orlive** [jamesflorentino/nanoScrollerJS#330]
is it possible to save scroll position of the view?

**Comment by kristerkari** [comment]
Thanks!

What do you mean by saving scroll position? Could you explain what you want to do?

**Comment by di3orlive** [comment]
@kristerkari lol it was more then half year ago 
don't remember )

**Comment by kristerkari** [comment]
@di3orlive In that case I'll close this issue :) Thanks anyway for submitting the issue 👍

**Comment by di3orlive** [comment]
@kristerkari np)
