### ISSUE TITLE
it has some delay in low internet speed mode!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [jamesflorentino/nanoScrollerJS#332]
nanoScrollerJS is fine! (Howerver, it has some delay in low internet speed mode!)

![https://cloud.githubusercontent.com/assets/18028768/22819672/263687ae-efae-11e6-946a-826f4a7fbfca.gif](https://cloud.githubusercontent.com/assets/18028768/22819672/263687ae-efae-11e6-946a-826f4a7fbfca.gif)

https://github.com/kamlekar/slim-scroll/issues/26

**Comment by xgqfrms-GitHub** [comment]
I think it shouldn't display the scrollbar style, until the js files loaded!

**Comment by kristerkari** [comment]
Thanks!

I don't see this as a big issue, as it is not a problem in the library, but rather in the website. :)
