### ISSUE TITLE
Child Scrolling issues.

### ISSUE THREAD

**Issue by IrvingArmenta** [jamesflorentino/nanoScrollerJS#333]
Hello, 

I'm building something that needs some "responsiveness" in height and also width, you can check the idea here:

https://jsfiddle.net/cduojzLa/

The (main) scrollbar works just as I want it, it works very good and I'm happy about that (main) box, however, the ".inner-scroll" div is not working at all, the content seems to overflow on the parent instead of making a scrollbar inside the yellow box (".widget") , I need the .inner-scroll to works just as the (main) one.

Is this a CSS issue? or is it a JavaScript issue? I'm not really sure why the content behaves like that, I think the .inner-scroll should work exactly as the (main) one.

**Latest Firefox and Chrome browsers.**

**Comment by michalkopanski** [comment]
@IrvingArmenta It looks to be a CSS issue. You simply don't have enough content to force an overflow.

You can check out https://jsfiddle.net/michalkopanski/3nzw3zc4/ for how you might be able to achieve what you're looking for. Notice that `.inner-scroll` is set to absolute to force an overflow.

nanoScrollerJS works as expected. _This issue can be closed._

**Comment by kristerkari** [comment]
I'm closing this as it seems to be resolved. Let's reopen if that is not the case.
