### ISSUE TITLE
Does not work with Kendo grid

### ISSUE THREAD

**Issue by basememara** [jamesflorentino/nanoScrollerJS#45]
Great plugin. I wish it would easily integrate into existing frameworks and websites though. It does not work in a Kendo UI grid. Any ideas on how to get this fixed?

Here is a live example of it:
http://jsfiddle.net/x9yL5/

**Comment by stuart-lawrence** [comment]
on the databound event on the Kendo Grid to this:

$("#" + gridID).find(".k-grid-header").after(THE NANO DIV with class =grid-scroller" <div class='grid-scroller'></div>");
    var outer = $("#" + gridID).find(".grid-scroller");
    $("#" + gridID).find(".k-grid-content").addClass("grid-scroller-content").prependTo($(outer));
    $(outer).nanoScroller({ contentClass: 'grid-scroller-content', paneClass: 'grid-scroller-pane', sliderClass: 'grid-scroller-slider' });
